### ISSUE TITLE
Stuck at flower screen

### ISSUE THREAD

**Issue by MendelGusmao** [lakkatv/Lakka#137]
I just installed Lakka in an Asus Eee PC 900A (Atom N270, 32-bit). It stops as soon as the flower appears and I can't do much as hit Ctrl+Alt+F# or Ctrl+Alt+Del. The HDD LED keeps blinking at a steady rate. No boot console.

**Comment by Kivutar** [comment]
The new nightlies should fix this bug:
http://sources.lakka.tv/nightly/Generic.x86_64/?C=N;O=D
http://sources.lakka.tv/nightly/Generic.i386/?C=N;O=D
Can you try it please?

**Comment by hdbreaker** [comment]
I, i have the same problem, I stay testing "stable" version on virtualbox (before i made convertion of .img to .vdi with VBoxManage). After first boot and resizing /storage reboot and stay on boot screen.
The interesting part is that VirtualMachine is responding to SSH, and i can move without problems, but boot screen...

I use: Lakka-Generic.x86_64-devel-20150307205641-r20834-ge8d52d6.img

I try Nightly version

**Comment by Kivutar** [comment]
Hi, @hdbreaker, we don't support virtualbox.

**Comment by hdbreaker** [comment]
Guys the problem persist in Lakka-Generic.x86_64-devel-20150512171823-r21002-ga5310d6.img on VirtualBox.

In teory you not support VirtualBox, but VirtualBox can emulate diferents arquitectures like, ARM, i368 and x64, VirtualBox must adapt to your system.

Anyway, Good job! when i have a little more time i probe this on my raspi, maybe a good idea is add support to beaglebone/beaglebone black!

Sorry for my bad english, im from Argentina!

**Comment by Kivutar** [comment]
Virtualbox can emulate many architectures, but either it is not ready for libdrm/kms, either we don't include some required software on the guest side. Anyway, the way we render to the screen makes RetroArch segfault on Virtualbox, VMWare and qemu.

**Comment by Jaypatto** [comment]
Guys I have the same issue as described above.

Fresh install of the current Lakka in an Asus Eee PC (Atom N2800, 32-bit). It stops as soon as the flower appears it freezes. The HDD LED keeps blinking at a steady rate. No boot console.

**Comment by Jaypatto** [comment]
update, after 10 minutes this message appears:

fbset: ioctl 0x4601 failed: Invalid argument

**Comment by Kivutar** [comment]
eeepc have intel gma right?

**Comment by Jaypatto** [comment]
yes i believe gma is used on the intel atom

**Comment by ygormutti** [comment]
Same problem and message here on another Asus Eee PC (Atom N2600) using live USB. Sometimes if I keep pressing Ctrl+Alt+F1 I'm able to see some boot messages that look a lot like systemd messages. The error message about ioctl appears before the systemd messages.

The same USB key boots on my desktop, but no sound. This is why I decided to try on the Eee.

Is there something I can do to provide you more details?

**Comment by Jaypatto** [comment]
Any suggestions? Would love to get this thing operational.

**Comment by Kivutar** [comment]
I need to add Intel gma drm support in the kernel. And check if it needs blobs too.

**Comment by Kivutar** [comment]
I need to know your exact Intel gma version. Some of them use i915, some are powervr. You can try our latest nightly build, it may fix your problem if your Intel gma require an i915 driver.

**Comment by Jaypatto** [comment]
Thanks for the follow up.

I don't have the eee pc with me today, so i will check when i get home.

Is there a bootable .img version of the latest nightly build i can try?

**Comment by Kivutar** [comment]
Yes, go there http://sources.lakka.tv/nightly/ and choose the latest img.gz for your architecture.

**Comment by Jaypatto** [comment]
Thanks, yep downloaded and tried but same result.

This info found on the Intel's website:
Intel® Atom™ Processor D2500/D2700/N2600/N2800 Series with Intel® Graphics Media Accelerator 3600/3650

no Linux support.

http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html?wapkw=n2800#atom

**Comment by Jaypatto** [comment]
You are correct, looks like powervr.

The Intel GMA 3600 series is a family of integrated video adapters based on the PowerVR SGX 545 graphics core. It is used in the Atom N2600 and Atom N2800.

found at:

https://wiki.archlinux.org/index.php/Intel_GMA3600

**Comment by Kivutar** [comment]
Yeah... Sorry but adding support for this graphic card would be too much work for us I think. And we will not be able to add graphical acceleration anyway. So if you really want to recycle the machine, I suggest you to setup any linux distro with a xorg server, and use retroarch without hardware acceleration on it.

**Comment by Jaypatto** [comment]
Spew, okay I was really hoping I could use this PC.

Thanks for your time, I appreciate your help and fast responses.

**Comment by Richard-L** [comment]
I have the same issue on an old laptop: http://www8.hp.com/h20195/v2/GetPDF.aspx/c04142055.pdf

**Comment by vahious** [comment]
how i can install nightly version ?  from windows to linux  like .iso  Win32DiskImager to usb and restart boot from usb and done ?

**Comment by vahious** [comment]
ok now i installed nightly version   we got new problem  the color of menu is all white i cant see  what i choose  if i go reboot for one sec is black background  then background turn auto white  and i cant see what a choose

**Comment by ronilaukkarinen** [comment]
Confirming the same problem in ASUS eee pc 901 if you choose wrong build, with x86_64. Choosing installer or live just make the menu disappear and stuck with tiny logo, if the build is x86_64. After mingling with tab and options, I get message:

````
This kernel requires an x86-64 CPU, but only detected an i686 CPU. Unable to boot - please use a kernel appropriate for your CPU.
````

So it's about architecture. Eee PC needs i386 which installs fine - for my bummer without DOSbox support as stated [here](https://github.com/libretro/Lakka/issues/354).

So, try i386. :)

**Comment by zx6802** [comment]
Can this issue be reopened? I tried Lakka-Generic.i386-2.0.img on an EeePC 701, which has a https://en.wikipedia.org/wiki/Intel_GMA#GMA_900 and got the same problem. Judging from [this thread](https://forums.libretro.com/t/lakka-on-old-pc-s/2803/12) however, it should work. I'm fully aware, that the speed might not be sufficient for the more fancy things, but I'm mainly interested in the old 8-bit stuff.

**Comment by Kivutar** [comment]
Can you open a new thread here and link to this issue please? https://github.com/libretro/Lakka-LibreELEC
